plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceBeforeBrackets:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  AllowedMethods:
    - translation_class
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  Max: 200
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ParameterLists:
  Max: 6

RSpec:
  Exclude:
    - spec/factories/**/*.rb

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - spec/system/**/*_spec.rb
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10
  Exclude:
    - spec/system/**/*_spec.rb

RSpec/MultipleMemoizedHelpers:
  Max: 25

RSpec/NestedGroups:
  Max: 6

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
